# ------------------------------------------------------------------------------
# Toolchain

[[Environment]]
name = "AS"
value = "${CCACHE} arm-none-eabi-gcc -x assembler-with-cpp"
description = "Assembler tool that supports cache"

[[Environment]]
name = "CC"
value = "${CCACHE} arm-none-eabi-gcc"
description = "C compiler tool that supports cache"

[[Environment]]
name = "CXX"
value = "${CCACHE} arm-none-eabi-g++"
description = "C++ compiler tool that supports cache"

[[Environment]]
name = "LD"
value = "arm-none-eabi-gcc"
description = "Linker tool"

[[Environment]]
name = "SZ"
value = "arm-none-eabi-size"
description = "Tool to measure binary file sizes"

[[Environment]]
name = "OC"
value = "arm-none-eabi-objcopy"
description = "Tool to copy and translate object files"

[[Environment]]
name = "NM"
value = "arm-none-eabi-nm"
description = "Tool to list symbols from object files"

# ------------------------------------------------------------------------------
# Makefile

[[Environment]]
name = "RUN_CMD"
value = 'uart -d "/dev/ttyACM0" -s "115200"'
description = "Command to run and connect with the board via serial interface"

[[Environment]]
name = "SIZE_CMD"
value = '${BUILDSYSTEM_DIRPATH}/scripts/get_fw_size "$<" 0x40000 0x8000 > "$@"'
description = "Command to measure the size of the elf"

# ------------------------------------------------------------------------------
# Linker script

[[Environment]]
name = "LDFLAGS"
value = "-Tport/${PORT_NAME}/TM4C123GH6PM.ld"
description = "Linker script"
method = "append"

# ------------------------------------------------------------------------------
# Reset Handler

#LDFLAGS += -e Reset_Handler

# ------------------------------------------------------------------------------
# C standard library

[[Environment]]
name = "LDFLAGS"
value = "-lc"
description = "C standard library"
method = "append"

[[Environment]]
name = "LDFLAGS"
value = "-lm"
description = "C standard math library"
method = "append"

# ------------------------------------------------------------------------------
# ARCH

[[Environment]]
name = "CPPFLAGS"
value = "-mcpu=cortex-m4"
description = "Microcontroller arch"
method = "append"

[[Environment]]
name = "CPPFLAGS"
value = "-mthumb"
description = "Thumb mode"
method = "append"

# FPU

[[Environment]]
name = "CPPFLAGS"
value = "-mfpu=fpv4-sp-d16"
description = "???"
method = "append"

[[Environment]]
name = "CPPFLAGS"
value = "-mfloat-abi=hard"
description = "???"
method = "append"

#CPPFLAGS += -mfloat-abi=softfp

# ------------------------------------------------------------------------------
# TODO

[[Environment]]
name = "CPPFLAGS"
value = "-fdata-sections"
description = "Data sections"
method = "append"

[[Environment]]
name = "CPPFLAGS"
value = "-ffunction-sections"
description = "Function sections"
method = "append"

[[Environment]]
name = "LDFLAGS"
value = "-u --gc-sections"
description = "Function sections"
method = "append"

[[Environment]]
name = "LDFLAGS"
value = "-Wl,--gc-sections"
description = "Function sections"
method = "append"

#LDFLAGS += -Wl,-u
#LDFLAGS += -Wl,_printf_float

[[Environment]]
name = "LDFLAGS"
value = "-u _printf_float"
description = "Print floats with printf"
method = "append"

[[Environment]]
name = "LDFLAGS"
value = "-u _scanf_float"
description = "Read floats with scanf"
method = "append"

#LDFLAGS += -ffreestanding
#LDFLAGS +=-nostdlib

[[Environment]]
name = "LDFLAGS"
value = "-specs=nosys.specs"
description = "????"
method = "append"

#LDFLAGS+=-specs=nano.specs

#LDFLAGS+=-lnosys
#LDFLAGS+=-lrdimon

# ------------------------------------------------------------------------------
# Thirdparty

# ------------------------------------------------------------------------------
# CMSIS

[[Environment]]
name = "CPPFLAGS"
value = "-DTM4C123GH6PM"
description = "Define the microcontroller"
method = "append"

[[Environment]]
name = "CPPFLAGS"
value = "-Ithirdparty/CMSIS/Device/TI/TM4C/Include/"
description = "CMSIS Path"
method = "append"

[[Environment]]
name = "CPPFLAGS"
value = "-Ithirdparty/CMSIS/Include/"
description = "CMSIS Path"
method = "append"

# ------------------------------------------------------------------------------
#    Tiva Libraries

#CPPFLAGS  += -Ithirdparty/Tiva/driverlib\
#             -Ithirdparty/Tiva/driverlib/gcc

#LDFLAGS   += -L thirdparty/Tiva/driverlib/gcc\
#             -ldriver

# ------------------------------------------------------------------------------
# Makefile rules

[[MakefileRule]]
phony = true
targets = "flash"
prerequisites = "$(BIN_OUTDIR)$(PROJ_NAME).bin"
command = """
	@lm4flash -v -E $<
"""
description = "Flashing with Segger"
