[[Toolchain]]
name = "AS"
cache = "ccache"
program = "arm-none-eabi-gcc"
arg = "-x assembler-with-cpp"

[[Toolchain]]
name = "CC"
cache = "ccache"
program = "arm-none-eabi-gcc"
arg = ""

[[Toolchain]]
name = "CXX"
cache = "ccache"
program = "arm-none-eabi-g++"
arg = ""

[[Toolchain]]
name = "LD"
cache = ""
program = "arm-none-eabi-g++"
arg = ""

[[Toolchain]]
name = "SZ"
cache = ""
program = "arm-none-eabi-size"
arg = ""

[[Toolchain]]
name = "OC"
cache = ""
program = "arm-none-eabi-objcopy"
arg = ""

[[Toolchain]]
name = "NM"
cache = ""
program = "arm-none-eabi-nm"
arg = ""


[[LDFLAGS]]
description = "Linker script"
arg = "-Tport/$(PORT_NAME)/TM4C123GH6PM.ld"

#[[LDFLAGS]]
#description = "Reset Handler"
#arg = "-e Reset_Handler"

#.................................................
#    C standard library

[[LDFLAGS]]
description = "C standard library"
arg = "-lc"

[[LDFLAGS]]
description = "C standard math library"
arg = "-lm"

#.................................................
#    ARCH

[[CPPFLAGS]]
description = "Microcontroller arch"
arg = "-mcpu=cortex-m4"

[[CPPFLAGS]]
description = "Thumb mode"
arg = "-mthumb"

[[CPPFLAGS]]
description = "FPU"
arg = "-mfpu=fpv4-sp-d16"

[[CPPFLAGS]]
description = "Hardware float support"
arg = "-mfloat-abi=hard"

#.................................................
#    TODO

[[CPPFLAGS]]
description = "Data sections"
arg = "-fdata-sections"

[[CPPFLAGS]]
description = "Function sections"
arg = "-ffunction-sections"

[[LDFLAGS]]
description = "Function sections"
arg = "-ffunction-sections"

[[LDFLAGS]]
description = "Garbage collection sections"
arg = "-u --gc-sections -Wl,--gc-sections"

[[CPPFLAGS]]
description = "Define the microcontroller"
arg = "-DTM4C123GH6PM"

#.................................................
#    CMSIS

[[CPPFLAGS]]
description = "CMSIS"
arg = "-Ithirdparty/CMSIS/Device/TI/TM4C/Include/"

[[CPPFLAGS]]
description = "File"
arg = "-Ithirdparty/CMSIS/Include/"

#.................................................
#    Tiva Libraries

[[CPPFLAGS]]
description = "File"
arg = "-Ithirdparty/Tiva/driverlib"

#CPPFLAGS  += -Ithirdparty/Tiva/driverlib\
#             -Ithirdparty/Tiva/driverlib/gcc

#LDFLAGS   += -L thirdparty/Tiva/driverlib/gcc\
#             -ldriver


################################################################################
#    Functions
#

# Function to run the program
override define runApp
  uart -d "/dev/ttyACM0" -s "115200"
endef

# Function to calculate the size of the elf
override define sizeElf
  @./scripts/get_fw_size "$(1)" 0x40000 0x8000 > "$(2)"
endef


################################################################################
#    Toolchain
#

.PHONY: flash
flash: $(BIN_OUTDIR)$(PROJ_NAME).bin
	@lm4flash -v -E $<
